import basic
import tactic.linarith
set_option pp.generalized_field_notation false

universe u

namespace rotation_lemmas
open btree

variables {α : Type u}

lemma forall_keys_trans (r : btree α) (p : nat → nat → Prop) (z x : nat) (h₁ : p x z) (h₂ : ∀ a b c, p a b → p b c → p a c) :
  forall_keys p z r → forall_keys p x r :=
begin
  induction r,
  case empty { simp [forall_keys], },
  case node : rl rk ra rr ihl ihr { 
    simp [forall_keys],
    intros h₃ h₄ h₅,
    split,
    { finish, },
    { split, 
      { apply h₂, apply h₁, finish, },
      { finish, },
    },
  },
end

lemma easyL_ordered (rl rr l : btree α) (k rk : nat) (a ra : α) :
  ordered (btree.node l k a (btree.node rl rk ra rr)) → 
    ordered (easyL (btree.node l k a (btree.node rl rk ra rr))) :=
begin
  intro h₁,
  simp only [easyL, ordered],
  simp only [ordered] at h₁,
  split,
  { split, 
    { apply and.left h₁, },
    { split, 
      { apply and.left (and.left (and.right h₁)), },
      { apply and.elim h₁,
        intros h₂ h₃,
        apply and.elim h₃,
        intros h₄ h₅,
        apply and.elim h₅,
        intros h₆ h₇,
        rw forall_keys at h₇,
        apply and.intro h₆ (and.left h₇), 
      },
    },
  },
  { apply and.intro,
    { finish, },
    { apply and.intro, 
      { rw forall_keys, 
        apply and.elim h₁,
        intros h₂ h₃,
        apply and.elim h₃,
        intros h₄ h₅,
        apply and.elim h₅,
        intros h₆ h₇,
        rw forall_keys at h₇,
        split,
        { apply forall_keys_trans _ (>) k _, 
          { apply and.left (and.right h₇), },
          { apply trans, },
          { exact h₆, },
        },
        { split, apply and.left (and.right h₇), finish, },
      },
      { finish, },
    } 
  },
end

lemma easyR_ordered (ll lr r : btree α) (k lk : nat) (a la : α) : 
  ordered (btree.node (btree.node ll lk la lr) k a r) → 
    ordered (easyR (btree.node (btree.node ll lk la lr) k a r)) :=
begin
  intro h₁,
  simp only [easyR, ordered],
  simp only [ordered] at h₁,
  apply and.intro,
  { apply and.left (and.left h₁), },
  { apply and.intro,
    { apply and.intro, 
      { apply and.left (and.right (and.left h₁)), },
      { apply and.intro, 
        { apply and.left (and.right h₁), },
        { apply and.intro,
          { apply and.elim h₁, 
            intros h₂ h₃,
            apply and.elim h₃,
            intros h₄ h₅,
            apply and.elim h₅,
            intros h₆ h₇,
            rw forall_keys at h₆,
            apply and.right (and.right h₆),
          },
          { finish, },
        },
      },
    },
    { apply and.intro, 
      { apply and.left (and.right (and.right (and.left h₁))), },
      { rw forall_keys, 
        apply and.intro,
        { apply and.right (and.right (and.right (and.left h₁))), },
        { apply and.elim h₁,
          intros h₂ h₃,
          apply and.elim h₃,
          intros h₄ h₅,
          apply and.elim h₅,
          intros h₆ h₇,
          rw forall_keys at h₆,
          apply and.intro,
          { apply and.left (and.right h₆), },
          { apply forall_keys_trans _ (<) k _, 
            { apply and.left (and.right h₆), },
            { apply has_lt.lt.trans, },
            { exact h₇, },
          }, 
        },
      },
    }, 
  },
end

lemma rotR_ordered (ll lr r : btree α) (k lk : nat) (a la : α) :
  ordered (btree.node (btree.node ll lk la lr) k a r) → 
    ordered (rotR (btree.node (btree.node ll lk la lr) k a r)) :=
begin 
  intros h₁,
  simp only [rotR],
  by_cases c₁ : (height ll < height lr),
  { simp only [if_pos c₁],
    cases lr,
    case empty {
      simp only [easyL],
      apply easyR_ordered,
      exact h₁,
    },
    case node : trl trk tra trr {
      apply easyR_ordered,
      simp only [ordered],
      simp only [ordered] at h₁,
      split,
      { split, 
        { split,
          { apply and.left (and.left h₁), },
          { split, 
            { apply and.left (and.left (and.right (and.left h₁))), },
            { split, 
              { finish, },
              { sorry },
            },
          }, 
        },
        { split, 
          { apply and.left (and.right (and.left (and.right (and.left h₁)))), },
          { split,
            { rw forall_keys,
              apply and.elim h₁,
              intros h₂ h₃,
              apply and.elim h₂,
              intros h₄ h₅,
              apply and.elim h₅,
              intros h₆ h₇,
              apply and.elim h₇,
              intros h₈ h₉,
              rw forall_keys at h₉, 
              split,
              { apply forall_keys_trans ll (>) lk _,
                { apply and.left (and.right h₉), },
                { apply trans, },
                { exact h₈, }, 
              },
              { split, 
                { apply and.left (and.right h₉), },
                { finish, },
              },
            },
            { finish, }, 
          },
        },
      },
      { split, 
        { apply and.left (and.right h₁), },
        { split,
          { apply and.elim h₁,
            intros h₂ h₃,
            apply and.elim h₃,
            intros h₄ h₅,
            apply and.elim h₅,
            intros h₆ h₇,
            rw forall_keys, 
            rw forall_keys at h₆,
            clear h₂ h₃ h₄ h₅ h₇,
            apply and.elim h₆,
            intros h₂ h₃,
            apply and.elim h₃,
            intros h₄ h₅,
            rw forall_keys at h₅,
            rw forall_keys,
            split,
            { apply and.intro h₂ (and.intro h₄ (and.left h₅)), },
            { apply and.intro (and.left (and.right h₅)) (and.right (and.right h₅)), },
          },
          { finish, }, 
        },
      },
    },
  },
  { simp only [if_neg c₁], 
    apply easyR_ordered,
    exact h₁,
  },
end

end rotation_lemmas